# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      env:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
